### ISSUE TITLE
Skill-Lib as NPM Package

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-skill-lib#9]
In selflearn we curently use submodules to include the skill-lib into the app. This was done to make the development more easy. This is not needed anymore and somewhere in the near future we want to merge functionalities into the master which needs the skill-lib. 

The next step should be to publish the skill lib as package somewhere (e.g. npmjs.org) and introduce a versioning scheme with release cycles. 

- [x] Choose a package name
- [x] Choose and document versioning schema
- [x] Upload the package to npmjs
- [x] Create CI auto-aupload

**Comment by Elscha** [comment]
* **Package name:** @e-learning-by-sse/nm-skill-lib
* **Versioning Spec:** https://github.com/e-Learning-by-SSE/nm-skill-lib/blob/main/semver.md
* **Location:** https://github.com/orgs/e-Learning-by-SSE/packages/npm/package/nm-skill-lib
